baseURL = "http://example.org/"
languageCode = "en-us"
title = "Language Comparison Quick Reference"
publishDir = "./site"
disableKinds = ["RSS", "sitemap", "taxonomy", "taxonomyTerm"]
pygmentsUseClasses = "true"
theme = "compare"
disableHugoGeneratorInject = true

[outputFormats]
	[outputFormats.CSS]
		path = "/css/"
		baseName = "compare"