baseURL = "https://acahir.github.io/languageCrossReference/"
languageCode = "en-us"
title = "Language Comparison Quick Reference"
publishDir = "./docs"
disableKinds = ["RSS", "sitemap", "taxonomy", "taxonomyTerm"]
pygmentsUseClasses = "true"
theme = "compare"
disableHugoGeneratorInject = true
